import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Richard Obiri <a href="#">Assignment!</a>
        </h1>

        <p className={styles.description}>
          Get started by Locating{' '}
          <code className={styles.code}>pages/api/...</code>
        </p>

        <div className={styles.grid}>
          <a href="https://documenter.getpostman.com/view/6960062/UVypyGgK" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about API Request and Responses</p>
          </a>
        
        
          <a
            href="https://musalasoft.vercel.app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Deployed to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}
